brew "direnv"
brew "rbenv"
brew "nvm"

brew "ack"
brew "cabal-install"
brew "curl"
brew "delve" # go debugger
brew "dfu-util"
brew "git"
brew "git-duet"
brew "graphviz" # for dot & tree-sitter grammar development
brew "idris"
brew "jq"
brew "libmagic"
brew "node"
brew "postgresql"
brew "python3"
brew "sequel-pro"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "vim"

cask "1Password"
cask "alfred"
cask "arq"
cask "atom"
cask "battle-net"
cask "dash"
cask "discord"
cask "docker"
cask "dropbox"
cask "emacs"
cask "evernote"
cask "github"
cask "google-chrome"
cask "iTerm2"
cask "kap"
cask "kindle"
cask "openemu"
cask "sketch"
cask "slack"
cask "spectacle"
cask "spotify"
cask "textmate"
cask "viscosity"
cask "zoom"
